In [14]:
    import kagglehub

    # Download latest version
    path = kagglehub.dataset_download("elvinrustam/books-dataset")

    print("Path to dataset files:", path)

Path to dataset files: C:\Users\ionut\.cache\kagglehub\datasets\elvinrustam\books-dataset\versions\3

In [20]:
import pandas as pd
import os

# Creeaza calea completa catre fisierul CSV
csv_file = os.path.join(path, "BooksDataset.csv")

# Incarca CSV-ul in Pandas
df = pd.read_csv(csv_file)

#Afiseaza primele randuri
df.head()

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
1,The Missing Person,"By Grumbach, Doris",NaN,"Fiction , General",Putnam Pub Group,"Sunday, March 1, 1981",Price Starting at $4.99
2,Don't Eat Your Heart Out Cookbook,"By Piscatella, Joseph C.",NaN,"Cooking , Reference",Workman Pub Co,"Thursday, September 1, 1983",Price Starting at $4.99
3,When Your Corporate Umbrella Begins to Leak: A...,"By Davis, Paul D.",NaN,NaN,Natl Pr Books,"Monday, April 1, 1991",Price Starting at $4.99
4,Amy Spangler's Breastfeeding : A Parent's Guide,"By Spangler, Amy",NaN,NaN,Amy Spangler,"Saturday, February 1, 1997",Price Starting at $5.32

In [21]:
#Afiseaza ultimele randuri
df.tail()

,Title,Authors,Description,Category,Publisher,Publish Date,Price
103077,Build 3 Super Serving Carts,By Chuck Hampton,NaN,NaN,ENDesigns Inc.,"Wednesday, January 1, 1992",Price Starting at $9.97
103078,My Land of Israel,"By Nover, Elizabeth Z.",NaN,"Juvenile Nonfiction , People & Places , Middl...",Behrman House,"Friday, May 1, 1987",Price Starting at $4.99
103079,Tongues: To Speak or Not to Speak,By Donald W. Burdick,NaN,NaN,Moody Press,"Wednesday, January 1, 1969",Price Starting at $5.29
103080,If I'm in charge here why is everybody laughing?,"By Campbell, David P.",NaN,NaN,Argus Communications,"Tuesday, January 1, 1980",Price Starting at $4.99
103081,Your First Puppy (Your First Series),"By Carpentier, Marcel",An introduction to the proper care of puppies ...,"Pets , Dogs , General",Tfh Pubns Inc,"Friday, November 1, 1991",Price Starting at $4.99

In [22]:


print(df)

                                                    Title  \
0                                           Goat Brothers
1                                      The Missing Person
2                       Don't Eat Your Heart Out Cookbook
3       When Your Corporate Umbrella Begins to Leak: A...
4         Amy Spangler's Breastfeeding : A Parent's Guide
...                                                   ...
103077                        Build 3 Super Serving Carts
103078                                  My Land of Israel
103079                  Tongues: To Speak or Not to Speak
103080   If I'm in charge here why is everybody laughing?
103081               Your First Puppy (Your First Series)

                         Authors  \
0               By Colton, Larry
1             By Grumbach, Doris
2       By Piscatella, Joseph C.
3              By Davis, Paul D.
4               By Spangler, Amy
...                          ...
103077          By Chuck Hampton
103078    By Nover, Elizabeth Z.
103079      By Donald W. Burdick
103080     By Campbell, David P.
103081     By Carpentier, Marcel

                                              Description  \
0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
103077                                                NaN
103078                                                NaN
103079                                                NaN
103080                                                NaN
103081  An introduction to the proper care of puppies ...

                                                 Category  \
0                                       History , General
1                                       Fiction , General
2                                     Cooking , Reference
3                                                     NaN
4                                                     NaN
...                                                   ...
103077                                                NaN
103078   Juvenile Nonfiction , People & Places , Middl...
103079                                                NaN
103080                                                NaN
103081                              Pets , Dogs , General

                   Publisher                 Publish Date  \
0                  Doubleday      Friday, January 1, 1993
1           Putnam Pub Group        Sunday, March 1, 1981
2             Workman Pub Co  Thursday, September 1, 1983
3              Natl Pr Books        Monday, April 1, 1991
4               Amy Spangler   Saturday, February 1, 1997
...                      ...                          ...
103077        ENDesigns Inc.   Wednesday, January 1, 1992
103078         Behrman House          Friday, May 1, 1987
103079           Moody Press   Wednesday, January 1, 1969
103080  Argus Communications     Tuesday, January 1, 1980
103081         Tfh Pubns Inc     Friday, November 1, 1991

                          Price
0       Price Starting at $8.79
1       Price Starting at $4.99
2       Price Starting at $4.99
3       Price Starting at $4.99
4       Price Starting at $5.32
...                         ...
103077  Price Starting at $9.97
103078  Price Starting at $4.99
103079  Price Starting at $5.29
103080  Price Starting at $4.99
103081  Price Starting at $4.99

[103082 rows x 7 columns]